// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package veicolo;



/************************************************************/
/**
 * 
 */
public class Automobile extends Veicolo
 {
				/**
				 * 
				 */
				private int prezzoOrario;
	/**
	 * 
	 * @return 
	 */
	public int getPrezzoOrario() {
	}
}
