// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package business.veicolo;

/************************************************************/
/**
 * 
 */
public class Automobile extends Veicolo {
	/**
	 * 
	 */
	private int prezzoOrario;

	public Automobile(String targa, String marca, String modello, int prezzoO, String pathImg, String alimentazione,
			String[] pathImgs) {
		super(targa, marca, modello, pathImg, alimentazione, pathImgs);
		this.prezzoOrario = prezzoO;
	}

	/**
	 * 
	 * @return
	 */
	public int getPrezzoOrario() {
		return prezzoOrario;
	}
}
